# Generated by Django 3.2.9 on 2021-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
