# Generated by Django 3.2.9 on 2021-11-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='num',
            field=models.BigIntegerField(),
        ),
    ]
