# Generated by Django 3.2.9 on 2021-11-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_testmodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
