# Generated by Django 3.2.9 on 2021-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_testmodel_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='is_mentor',
            field=models.BooleanField(null=True),
        ),
    ]
