# Generated by Django 3.2.9 on 2021-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_testmodel_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='Dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
