# Generated by Django 3.2.9 on 2021-11-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_testmodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='document',
            field=models.FileField(default='cvc', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
