# Generated by Django 3.2.9 on 2021-11-25 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_testmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('394f74b9-b0d1-49e6-a4d5-fb867a4ed6df'), primary_key=True, serialize=False),
        ),
    ]
