# Generated by Django 3.2.9 on 2021-11-25 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_testmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88c99144-c426-4b2c-b784-287a4971fb95'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.manufacturer')),
            ],
        ),
    ]
