# Generated by Django 3.2.9 on 2021-11-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='VVV', max_length=128),
            preserve_default=False,
        ),
    ]
