# Generated by Django 5.0.2 on 2024-03-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_promoter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('faq_type', models.CharField(choices=[('rent_tracking', 'Rent Tracking'), ('new_deposite', 'New Deposite'), ('existing_deposite', 'Exisiting Deposite')], max_length=255)),
            ],
        ),
    ]
